"""empty message

Revision ID: 0393ab7a4000
Revises: 720e2b7049f8
Create Date: 2023-09-10 14:05:24.903064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0393ab7a4000'
down_revision = '720e2b7049f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('game_creator_id_key', type_='unique')
        batch_op.drop_constraint('game_receiver_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint('game_receiver_id_key', ['receiver_id'])
        batch_op.create_unique_constraint('game_creator_id_key', ['creator_id'])

    # ### end Alembic commands ###
