"""empty message

Revision ID: cfada50bf8d7
Revises: 0393ab7a4000
Create Date: 2023-09-10 14:16:50.636946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfada50bf8d7'
down_revision = '0393ab7a4000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
